### ISSUE TITLE
Validity of code examples while versions change

### ISSUE THREAD

**Issue by githubrsys** [FluidTYPO3/fluidtypo3org#28]
# Summary

Library · Code examples > Has no mandatory information with which version a snippet is valid. 

### Solution

* Add a mandatory field of the used versions of flux, vhs and so on. 

### Thoughs

* Put a section within a snippet where blog articles are shown which take the different changes of the used extensions into account.

**Comment by NamelessCoder** [comment]
We expect this to function follows:

* Code library examples must always work in the latest released TER versions.
* The library is not intended to store examples for legacy (non-current) TER versions.
* Gist (when not anonymous) has an author who should be responsible for updating the Gist if needed.
* Anonymous gists will most likely just be removed when incompatibilities arise.
* Gists have a change history which would identify when and why the Gist was updated (for compatibility or whatever reason). If the update is one concerned with compatibility, the Gist author should refer to the change either by commit, pull request, blog article or any outside source.

Basically we want to avoid storing this metadata on our side. What we do have is the extension context - and it is there mainly for filtering purposes and also doubles as a facet for solr results coming from the code library (which is, in turn, the reason it should be stored on our side - for easier indexing).

It would be possible to:

* Render the change log of a gist (I believe this is public info but if not, can be achieved via the GitHub API).
* Place a common notice about what to do if the example doesn't work, instructing the visitor to contact the author if there is one, or somehow notify the team (we could add a button for that, something like "Report broken example" which requires the visitor to describe how it is broken and to confirm that it's broken in the latest released versions, e.g. he isn't reporting it broken based on some old version).

These features would be possible to implement in EXT:fluidshare and we would appreciate pull requests which add them. As a start, perhaps you could file these as two feature request issues for the EXT:fluidshare repository ;)
