### ISSUE TITLE
Github links missing on website

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidtypo3org#30]
I fail to find links to the github repositories on https://fluidtypo3.org/

There should be links to them in https://fluidtypo3.org/community.html, or even an own main menu entry "Source code".

Also, https://fluidtypo3.org/documentation/installation/from-github.html does not link to the github repositories (none I can click on).

----
Moved from https://github.com/FluidTYPO3/documentation/issues/58

**Comment by cweiske** [comment]
Still no link to github.

**Comment by NamelessCoder** [comment]
Closing (2/4), copied to internal add/avoid/fix list for coming web site overhaul. Thanks for reporting!

**Comment by cweiske** [comment]
A year is gone :)
