### ISSUE TITLE
Link to original fluid viewhelper documentation

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidtypo3org#33]
It would be nice if the *fluid* viewhelpers would have a link to their original typo3.org documentation

https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Index.html

E.g. https://fluidtypo3.org/viewhelpers/fluid/master/AliasViewHelper.html should have a link to https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Alias.html

**Comment by NamelessCoder** [comment]
I'm afraid we can't fulfil this request - we do not control the source code of the Fluid ViewHelpers which is where the documentation text comes from. We *could* generate an expected link but not only is the target documentation out of date, to my knowledge it is not versioned which means we cannot link to the correct version of the target docs from the same version of fluid schema docs.

If you have a suggestion for this I'm always happy to discuss it, but if the alternative to no links is links that go nowhere or to the wrong version of docs I think I would prefer no links (and instead link to those docs from somewhere other than each individual ViewHelper's detail page). Catch me on IRC if needed!
