### ISSUE TITLE
vhs 3.1.0 missing on  https://fluidtypo3.org/viewhelpers/vhs/

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidtypo3org#36]
vhs 3.1.0 is missing on https://fluidtypo3.org/viewhelpers/vhs/ and so "master" does not reflect reality.

**Comment by NamelessCoder** [comment]
Updated (and I finally got around to making all the necessary dependencies and a tiny script that does these things automatically with minimal user input, so hopefully the docs won't go out of date like this any more).
