### ISSUE TITLE
Fluid Content Provider Extension crashes on TYPO3 8.7.17

### ISSUE THREAD

**Issue by soerenwach** [FluidTYPO3/fluidtypo3org#44]
Hello,

I have a problem with the provider Extension for FLuidContent Elements.
I used the "builder" Extension to create a Fluid Content Provider Extension with the following clean TYPO3 8.7.17 setup:
Flux 9.0.0
fluidpages 4.2.0
fluidcontent 5.2.0
vhs 5.0.1

When I'm installing the extension it breaks the whole TYPO3 with the following Exeption.
Any hint would be appreciated.

Best regards,
Sören

`Uncaught TYPO3 Exception
Class 'FluidTYPO3\Flux\View\TemplatePaths' not found 

Error thrown in file
/html/typo3/typo3conf/ext/fluidcontent/Classes/Service/ConfigurationService.php in line 327.

13 FluidTYPO3\Fluidcontent\Service\ConfigurationService::getContentElementFormInstances()

/html/typo3/typo3conf/ext/fluidcontent/Classes/Service/ConfigurationService.php:
00281:     {
00282:         $wizardTabs = [];
00283:         $forms = $this->getContentElementFormInstances();
00284:         foreach ($forms as $extensionKey => $formSet) {
00285:             $formSet = $this->sortObjectsByProperty($formSet, 'options.Fluidcontent.sorting', 'ASC');

12 FluidTYPO3\Fluidcontent\Service\ConfigurationService::buildAllWizardTabGroups()

/html/typo3/typo3conf/ext/fluidcontent/Classes/Service/ConfigurationService.php:
00193:         $pageTsConfig = '';
00194:         try {
00195:             $wizardTabs = $this->buildAllWizardTabGroups();
00196:             $collectionPageTsConfig = $this->buildAllWizardTabsPageTsConfig($wizardTabs);
00197:             $pageTsConfig .= '[PIDinRootline = ' . strval($pageUid) . ']' . LF;

11 FluidTYPO3\Fluidcontent\Service\ConfigurationService::renderPageTypoScriptForPageUid(12)

/html/typo3/typo3conf/ext/fluidcontent/Classes/Service/ConfigurationService.php:
00160:                     continue;
00161:                 }
00162:                 $pageTsConfig .= $this->renderPageTypoScriptForPageUid($pageUid);
00163:                 $processed[$pageUid] = 1;
00164:             }

10 FluidTYPO3\Fluidcontent\Service\ConfigurationService::getPageTsConfig()

/html/typo3/typo3conf/ext/fluidcontent/Classes/Backend/TableConfigurationPostProcessor.php:
00027:     public function processData()
00028:     {
00029:         ExtensionManagementUtility::addPageTSConfig($this->getConfigurationService()->getPageTsConfig());
00030:     }
00031: 

9 FluidTYPO3\Fluidcontent\Backend\TableConfigurationPostProcessor::processData()

/html/typo3/typo3_src-8.7.17/typo3/sysext/core/Classes/Core/Bootstrap.php:
00989:                     );
00990:                 }
00991:                 $hookObject->processData();
00992:             }
00993:         }

8 TYPO3\CMS\Core\Core\Bootstrap::runExtTablesPostProcessingHooks()

/html/typo3/typo3_src-8.7.17/typo3/sysext/core/Classes/Core/Bootstrap.php:
00968:     {
00969:         ExtensionManagementUtility::loadExtTables($allowCaching);
00970:         $this->runExtTablesPostProcessingHooks();
00971:         return $this;
00972:     }

7 TYPO3\CMS\Core\Core\Bootstrap::loadExtTables()

/html/typo3/typo3_src-8.7.17/typo3/sysext/backend/Classes/Http/RequestHandler.php:
00091:             ->initializeBackendRouter()
00092:             ->loadBaseTca()
00093:             ->loadExtTables()
00094:             ->initializeBackendUser()
00095:             ->initializeBackendAuthentication($proceedIfNoUserIsLoggedIn)

6 TYPO3\CMS\Backend\Http\RequestHandler::boot(boolean)

/html/typo3/typo3_src-8.7.17/typo3/sysext/backend/Classes/Http/RequestHandler.php:
00066:         // skip the BE user check on the login page
00067:         // should be handled differently in the future by checking the Bootstrap directly
00068:         $this->boot($pathToRoute === '/login');
00069: 
00070:         // Check if the router has the available route and dispatch.

5 TYPO3\CMS\Backend\Http\RequestHandler::handleRequest(TYPO3\CMS\Core\Http\ServerRequest)

/html/typo3/typo3_src-8.7.17/typo3/sysext/core/Classes/Core/Bootstrap.php:
00314: 
00315:         // Execute the command which returns a Response object or NULL
00316:         $this->response = $requestHandler->handleRequest($request);
00317:         return $this;
00318:     }

4 TYPO3\CMS\Core\Core\Bootstrap::handleRequest(TYPO3\CMS\Core\Http\ServerRequest)

/html/typo3/typo3_src-8.7.17/typo3/sysext/backend/Classes/Http/Application.php:
00090:         }
00091: 
00092:         $this->bootstrap->handleRequest($this->request);
00093: 
00094:         if ($execute !== null) {

3 TYPO3\CMS\Backend\Http\Application::run()

/html/typo3/typo3_src-8.7.17/typo3/sysext/backend/Resources/Private/Php/backend.php:
00022:     $classLoader = require __DIR__ . '/../../../../../../vendor/autoload.php';
00023: 
00024:     (new \TYPO3\CMS\Backend\Http\Application($classLoader))->run();
00025: });

2 {closure}()

/html/typo3/typo3_src-8.7.17/typo3/sysext/backend/Resources/Private/Php/backend.php:
00023: 
00024:     (new \TYPO3\CMS\Backend\Http\Application($classLoader))->run();
00025: });

1 require("/html/typo3/typo3_src-8.7.17/typo3/sysext/backend/Resources/Private/Php/backend.php")

/html/typo3/typo3_src-8.7.17/typo3/index.php:
00001: <?php
00002: 
00003: require __DIR__ . '/sysext/backend/Resources/Private/Php/backend.php';`

**Comment by NamelessCoder** [comment]
Fluidcontent is obsolete and uses classes that no longer exist in Flux 9.0 - you can still generate the provider extension with content templates, but you have to manually remove fluidcontent from the dependencies list in composer.json and ext_emconf.php.

**Comment by soerenwach** [comment]
Thanks for your quick response and the good hint.
After I made that changes I'm stucking with another problem:
It throws an error that actually makes no sense to me because that file, and that Class exist:

Fatal error: Class 'FluidTYPO3\Fluidcontent\Controller\ContentController' not found in /html/typo3/typo3conf/ext/sw_fluidfces/Classes/Controller/ContentController.php on line 35

Thank you very much and best regards,
Sören

**Comment by NamelessCoder** [comment]
Sounds like you enabled controller class generation as well - in which case you also need to change the parent class of the ContentController class that was generated. It should use the ContentController class from Flux as parent instead.

**Comment by soerenwach** [comment]
So I'm using this now and getting the same error:

`<?php
namespace FluidTYPO3\Flux\Controller;

/***************************************************************
 *  Copyright notice
 ***************************************************************/

use FluidTYPO3\Fluidcontent\Controller\ContentController as AbstractController;

/**
 * Content Controller
 *
 * @route off
 */
class ContentController extends AbstractController {

}`

**Comment by soerenwach** [comment]
Well, I just deleted the Classes Folder and it works as it should.
Thank you again for your help!
Have a nice day,
Sören

**Comment by NamelessCoder** [comment]
I'm guessing now, but it seems you changed the PHP namespace of the class instead of changing the class that is imported with `use`. If you need the controller class you'll need to be aware of that - but yes, most common use cases work just fine without a controller class.
