### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by janisint** [FluidTYPO3/fluidtypo3org#46]
Sadly, the website is currently not available.

![image](https://user-images.githubusercontent.com/65291198/91938530-72c65f80-ecf4-11ea-98e5-8ccf1a468123.png)

**Comment by janisint** [comment]
Up again.

**Comment by Eumolp** [comment]
the fluid/vhs documentation is down or not complete.
Is this project discontinued? Hopefully not!

**Comment by janisint** [comment]
I'm quite sure that they updated or deleted the viewhelper reference part of the documentation, which I find weird since right now its really weird to use and no links work anymore.

**Comment by NamelessCoder** [comment]
The VH docs are moved to a static export on a sub-domain, you can find all of them on https://viewhelpers.fluidtypo3.org - some of the redirects are still not functional since the `master` and `development` schemas are not currently being generated.
